apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-jenkins
  namespace: argocd
spec: 
  destination: 
    namespace: jenkins
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: ../../devops-tools/jenkins/helm-manifests
    repoURL: "https://github.com/opeomotayo/playground.git"
    targetRevision: HEAD
    helm:
      releaseName: jenkinsci
      valuesFiles:
        - ../../devops-tools/jenkins/jenkins-values.yaml
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validation=false
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - Replace=true
