apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: sonarqube
  namespace: argocd
spec: 
  destination: 
    namespace: sonarqube
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    repoURL: "https://opeomotayo.github.io/tools-chart/"
    targetRevision: 0.0.2
    chart: sonar-chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
