apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kustomize-guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: applications/kustomize-guestbook
    repoURL: "https://github.com/opeomotayo/playground.git"
    targetRevision: master
    kustomize:
      namePrefix: staging-
      commonLabels:
        app: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
