apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: jenkins-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins-operator
    app.kubernetes.io/version: 0.7.0
    helm.sh/chart: jenkins-operator-0.6.0
  name: jenkins-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jenkins-operator
      app.kubernetes.io/name: jenkins-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: jenkins-operator
        app.kubernetes.io/name: jenkins-operator
    spec:
      containers:
      - args: null
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: null
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: jenkins-operator
        image: virtuslab/jenkins-operator:v0.7.0
        imagePullPolicy: IfNotPresent
        name: jenkins-operator
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
      serviceAccountName: jenkins-operator

