apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: $(tf_jenkins_ip_whitelist)
spec:
  tls:
  - hosts:
    -  $(tf_jenkins_fqdn)
    secretName: frontend-tls
  rules:
  - host: $(tf_jenkins_fqdn)
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-operator-http-jenkins
          servicePort: 8080
