apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-backup
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

