apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: role-project
  namespace: argocd
spec:
  description: Project with role
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles:
  - name: ci-role
    description: Allows only Sync privileges for role-project
    policies:
    - p, proj:role-project:ci-role, applications, sync, role-project/*, allow

  orphanedResources:
    warn: false
