apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    plugins:
      - name: github
        version: 1.30.0
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 300
        periodSeconds: 50
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 8
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 300
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator-example
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins & Webhook Relay Operators repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/webhookrelay/jenkins-operator-example.git
    githubPushTrigger: true
