apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-auth
data:
  1-user-access.yaml: |-
    jenkins:
      agentProtocols:
      - "JNLP4-connect"
      - "Ping"
      authorizationStrategy:
        projectMatrix:
          permissions:
          - "Overall/Administer:jenkins-operator"
          - "Overall/Administer:/Auth/Jenkins/NS"
      securityRealm: "keycloak"
    unclassified:
      keycloakSecurityRealm:
        keycloakJson: |-
          {
            "realm": "N-able",
            "auth-server-url": "https://auth.dev.builtwith.solar/auth/",
            "ssl-required": "all",
            "resource": "",
            "public-client": true,
            "confidential-port": 0
          }
        keycloakRespectAccessTokenTimeout: true
        keycloakValidate: false
