apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-security
data:
  1-security.yaml: |-
    security:
      apiToken:
        creationOfLegacyTokenEnabled: true
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      envInject:
        enableLoadingFromMaster: false
        enablePermissions: false
        hideInjectedVars: false
      globalJobDslSecurityConfiguration:
        useScriptSecurity: false
      queueItemAuthenticator:
        authenticators:
        - global:
            strategy: "systemAuthorizationStrategy"
      sSHD:
        port: -1
      scriptApproval:
        approvedSignatures: []
