apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins-operator

images:
- name: virtuslab/jenkins-operator
  newTag: 13f871b

resources:
  - ../../base
  - resources/namespace.yaml
