pipeline {
  agent {
    kubernetes {
      yamlFile 'build-pod.yaml'
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
      }
    }
  }
}
