apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-audit-trail
data:
  1-audit-trail.yaml: |-
    unclassified:
      audit-trail:
        logBuildCause: true
        pattern: ".*/(?:configSubmit|doDelete|postBuildResult|enable|disable|cancelQueue|stop|toggleLogKeep|doWipeOutWorkspace|createItem|createView|toggleOffline|cancelQuietDown|quietDown|restart|exit|safeExit)"
