apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-base-libraries
data:
  1-global-libraries.yaml: |-
    unclassified:
      globalLibraries:
        libraries:
        - defaultVersion: "master"
          implicit: true
          includeInChangesets: false
          name: "pipeline-shared-libs"
          retriever:
            legacySCM:
              scm:
                git:
                  branches:
                  - name: "master"
                  buildChooser: "default"
                  userRemoteConfigs:
                  - credentialsId: "gh-repo-cred"
                    url: "https://github.com/opeomotayo/playground.git"
