controller:
  ingress:
    enabled: true
    paths:
    - path: "/"
      pathType: Prefix
      backend:
        service:
          name: >-
            {{ template "jenkins.fullname" . }}
          port:
            number: 8080
    apiVersion: "networking.k8s.io/v1"
    annotations:
      kubernetes.io/ingress.class: nginx
    # configures the hostname e.g. jenkins.example.com
    hostName: jenkins.opeomotayo.net
