apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  serviceAccountName: svc-gke-local-resourcecreator
  securityContext:
    runAsUser: 0
  volumes:
    - name: dind-storage
      emptyDir: {}
  containers:
    - name: jnlp
      image: harbor.mgmt-bld.oncp.dev/platform_tools_rtl/jnlp:release_v0.6.0
      tty: true
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
    - name: trufflehog
      image: harbor.mgmt-bld.oncp.dev/platform_tools/trufflehog:v0.14.0
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    - name: infra-tools
      image: harbor.mgmt-bld.oncp.dev/platform_tools_rtl/terraform-tools:release_v1.51.0
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "200Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    - name: changelog
      image: harbor.mgmt-bld.oncp.dev/platform_tools/standard-version:v0.1.0
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "250m"
