apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bld-base #git@github.com:/logicnow/bld-base.git?ref=v0.4.5
- jenkins/casc/location.yaml
- jenkins/casc/cloud.yaml
#- jenkins/credentials/gh-svc-nscommon-key.yaml
#- jenkins/credentials/gh-svc-nscommon-pat.yaml
#- jenkins/credentials/gitguardian-api-key.yaml
#- jenkins/credentials/gh-svc-nable-logicnow-key.yaml

#patchesStrategicMerge:
#- jenkins/casc/auth.yaml

patches:
- target:
    kind: Jenkins
    name: jenkins
  path: jenkins/patches/seed.yaml
- target:
    kind: Jenkins
    name: jenkins
  path: jenkins/patches/clouds.yaml
- target:
    kind: Jenkins
    name: jenkins
  path: jenkins/patches/location.yaml
