apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: flask-webapp
  namespace: argocd
spec: 
  destination: 
    namespace: flask
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: flask-manifest
    repoURL: "https://github.com/opeomotayo/playground-dependency.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validation=false
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - Replace=true
