apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: git-guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: applications/git-guestbook
    repoURL: "https://github.com/opeomotayo/playground.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
