apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  tls:
    - hosts:
      - fake
      secretName: api-tls-secret
  rules:
  - host: api.localtest.me
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: gateway
            port:
              number: 80
