apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/opeomotayo/playground.git
  password: # my pat token  NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops.
  username: # my username
