apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/jenkins
- resources/namespace/namespace.yaml
- resources/ingress/jenkins-ingress.yaml
- resources/ingress/production-issuer.yaml
- resources/ingress/production-certificate.yaml  
#- resources/ingress/frontend.yaml
