apiVersion: v1
data:
  1-mail-cloud.yaml: |-
    jenkins:
      clouds:
        - kubernetes:
            name: "global-planet"
            namespace: "build-gloabl-planet"
            usageRestricted: true
            jenkinsURL: "http://jenkins-operator-http-jenkins.jenkins.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-operator-slave-jenkins.jenkins.svc.cluster.local:50000"
            defaultsProviderTemplate: "default"
            templates:
              - name: "default"
                instanceCap: 10
                instanceCapStr: "10"
                workspaceVolume:
                  emptyDirWorkspaceVolume:
                    memory: false
                yamlMergeStrategy: "override"
            usageRestricted: true
kind: ConfigMap
metadata:
  labels:
    app: jenkins-operator
    jenkins-cr: jenkins
    watch: "true"
  name: global-planet-cloud
  namespace: jenkins

