apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-reporter-production
  namespace: policy-reporter
spec:
  secretName: policy-reporter-production-certificate
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - kyverno-policy-reporter.opeomotayo.net
    
